apiVersion: v1
kind: Service
metadata:
  name: msdemo-checkoutservice-service
  labels:
    app: msdemo-checkoutservice
spec:
  selector:
    app: msdemo-checkoutservice
  ports:
    - protocol: TCP
      port: 9555
  type: ClusterIP